port: 8080

static:
  base-url: http://localhost:8080
  route: /static
  filepath: ./tmp/public

gin:
  log-level: debug
gorm:
  log-level: warn
mysql:
  host: mysql:3306
  database: douyin_db
  username: user
  password: usr_pwd

jwt:
  issuer: douyin
  secret: example
  expires-in: 2h
