port: 8080

static:
  base-url: http://localhost:8080
  route: /static
  filepath: ./tmp/public

gorm:
  log-level: info
mysql:
  host: localhost:3306
  database: douyin_db
  username: root
  password: admin

jwt:
  issuer: douyin
  secret: example
  expires-in: 2h
